name: Quest
favicon: null
layout_spectrum: 0.50194
typography_spectrum: 0.3620072
title: QUEST
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#014f9a'
    - '#86bce2'
    - '#f6d400'
    - '#667208'
    - '#9e0017'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.4142706
purpose: []
